//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStore.POCOS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.1.201/webservice/advantechwebservice.asmx")]
        public string esPOCOS_AdvantechPartner_AdvantechWebService {
            get {
                return ((string)(this["esPOCOS_AdvantechPartner_AdvantechWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ags.advantech.com/WebService/PAPSService.asmx")]
        public string esPOCOS_AdvantechPAPS_PAPSService {
            get {
                return ((string)(this["esPOCOS_AdvantechPAPS_PAPSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pis.advantech.com/WS/PISProductWS.asmx")]
        public string esPOCOS_AdvantechPIS_PISProductWS {
            get {
                return ((string)(this["esPOCOS_AdvantechPIS_PISProductWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.21.1.93/USADVPrice/eBizAEU_WS.asmx")]
        public string esPOCOS_AdvantechSAPPrice_USAdvPrice {
            get {
                return ((string)(this["esPOCOS_AdvantechSAPPrice_USAdvPrice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.1.215:2009/ez_ws.asmx")]
        public string esPOCOS_EZWS_EZ_WS {
            get {
                return ((string)(this["esPOCOS_EZWS_EZ_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://my.advantech.com.tw/Services/MyDataMining.asmx")]
        public string esPOCOS_MyDataMining_MyDataMining {
            get {
                return ((string)(this["esPOCOS_MyDataMining_MyDataMining"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www2.advantech.com/webservice/AdvantechWebServiceLocal.asmx")]
        public string esPOCOS_WWWCMS_AdvantechWebServiceLocal {
            get {
                return ((string)(this["esPOCOS_WWWCMS_AdvantechWebServiceLocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://my.advantech.com/services/eBizAEU_WS.asmx")]
        public string esPOCOS_AdvantechSAPPriceMy_eBizAEU_WS {
            get {
                return ((string)(this["esPOCOS_AdvantechSAPPriceMy_eBizAEU_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://admin.advantech.com.tw/ws/AdminWebService.asmx")]
        public string esPOCOS_WWWCMSNew_AdminWebService {
            get {
                return ((string)(this["esPOCOS_WWWCMSNew_AdminWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://eq.advantech.com:8300/Services/ForeStore.asmx")]
        public string esPOCOS_EQ_ForeStore {
            get {
                return ((string)(this["esPOCOS_EQ_ForeStore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://my.advantech.com/Services/MYSAPDAL.asmx")]
        public string esPOCOS_MySAPDAL_MYSAPDAL {
            get {
                return ((string)(this["esPOCOS_MySAPDAL_MYSAPDAL"]));
            }
        }
    }
}
