//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class AffiliateTransaction
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AffiliateID
        {
            get { return _affiliateID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_affiliateID != value)
                    {
                        if (Affiliate != null && Affiliate.ID != value)
                        {
                            Affiliate = null;
                        }
                        _affiliateID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _affiliateID;
    
        public virtual string SiteID
        {
            get;
            set;
        }
    
        public virtual string TrackingID
        {
            get;
            set;
        }
    
        public virtual string OrderNO
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> OrderAmount
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(AffiliateTransaction); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual Affiliate Affiliate
        {
            get { return _affiliate; }
            set
            {
                if (!ReferenceEquals(_affiliate, value))
                {
                    var previousValue = _affiliate;
                    _affiliate = value;
                    FixupAffiliate(previousValue);
                }
            }
        }
        private Affiliate _affiliate;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupAffiliate(Affiliate previousValue)
        {
            if (previousValue != null && previousValue.AffiliateTransactions.Contains(this))
            {
                previousValue.AffiliateTransactions.Remove(this);
            }
    
            if (Affiliate != null)
            {
                if (!Affiliate.AffiliateTransactions.Contains(this))
                {
                    Affiliate.AffiliateTransactions.Add(this);
                }
                if (AffiliateID != Affiliate.ID)
                {
                    AffiliateID = Affiliate.ID;
                }
            }
            else if (!_settingFK)
            {
                AffiliateID = null;
            }
        }

        #endregion

    }
}
