//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class Application : ProductCategory
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual Nullable<int> ImageWidth
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ImageHeight
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PointTop
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PointLeft
        {
            get;
            set;
        }
    
        public virtual string BackgroundImage
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(Application); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ApplicationSpot> ApplicationSpots
        {
            get
            {
                if (_applicationSpots == null)
                {
                    var newCollection = new FixupCollection<ApplicationSpot>();
                    newCollection.CollectionChanged += FixupApplicationSpots;
                    _applicationSpots = newCollection;
                }
                return _applicationSpots;
            }
            set
            {
                if (!ReferenceEquals(_applicationSpots, value))
                {
                    var previousValue = _applicationSpots as FixupCollection<ApplicationSpot>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupApplicationSpots;
                    }
                    _applicationSpots = value;
                    var newValue = value as FixupCollection<ApplicationSpot>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupApplicationSpots;
                    }
                }
            }
        }
        private ICollection<ApplicationSpot> _applicationSpots;
    
        public virtual ICollection<ScenarioCategory> ScenarioCategories
        {
            get
            {
                if (_scenarioCategories == null)
                {
                    var newCollection = new FixupCollection<ScenarioCategory>();
                    newCollection.CollectionChanged += FixupScenarioCategories;
                    _scenarioCategories = newCollection;
                }
                return _scenarioCategories;
            }
            set
            {
                if (!ReferenceEquals(_scenarioCategories, value))
                {
                    var previousValue = _scenarioCategories as FixupCollection<ScenarioCategory>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupScenarioCategories;
                    }
                    _scenarioCategories = value;
                    var newValue = value as FixupCollection<ScenarioCategory>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupScenarioCategories;
                    }
                }
            }
        }
        private ICollection<ScenarioCategory> _scenarioCategories;
    
        public virtual ICollection<ScenarioSpotMapping> ScenarioSpotMappings
        {
            get
            {
                if (_scenarioSpotMappings == null)
                {
                    var newCollection = new FixupCollection<ScenarioSpotMapping>();
                    newCollection.CollectionChanged += FixupScenarioSpotMappings;
                    _scenarioSpotMappings = newCollection;
                }
                return _scenarioSpotMappings;
            }
            set
            {
                if (!ReferenceEquals(_scenarioSpotMappings, value))
                {
                    var previousValue = _scenarioSpotMappings as FixupCollection<ScenarioSpotMapping>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupScenarioSpotMappings;
                    }
                    _scenarioSpotMappings = value;
                    var newValue = value as FixupCollection<ScenarioSpotMapping>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupScenarioSpotMappings;
                    }
                }
            }
        }
        private ICollection<ScenarioSpotMapping> _scenarioSpotMappings;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupApplicationSpots(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ApplicationSpot item in e.NewItems)
                {
                    item.Application = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ApplicationSpot item in e.OldItems)
                {
                    if (ReferenceEquals(item.Application, this))
                    {
                        item.Application = null;
                    }
                }
            }
        }
    
        private void FixupScenarioCategories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ScenarioCategory item in e.NewItems)
                {
                    item.Scenario = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ScenarioCategory item in e.OldItems)
                {
                    if (ReferenceEquals(item.Scenario, this))
                    {
                        item.Scenario = null;
                    }
                }
            }
        }
    
        private void FixupScenarioSpotMappings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ScenarioSpotMapping item in e.NewItems)
                {
                    item.Application = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ScenarioSpotMapping item in e.OldItems)
                {
                    if (ReferenceEquals(item.Application, this))
                    {
                        item.Application = null;
                    }
                }
            }
        }

        #endregion

    }
}
