//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class CampaignMailLog
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual Nullable<int> CampaignID
        {
            get { return _campaignID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_campaignID != value)
                    {
                        if (Campaign != null && Campaign.CampaignID != value)
                        {
                            Campaign = null;
                        }
                        _campaignID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _campaignID;
    
        public virtual string StoreID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string UserId
        {
            get;
            set;
        }
    
        public virtual string PromotionCode
        {
            get;
            set;
        }
    
        public virtual int ID
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(CampaignMailLog); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual Campaign Campaign
        {
            get { return _campaign; }
            set
            {
                if (!ReferenceEquals(_campaign, value))
                {
                    var previousValue = _campaign;
                    _campaign = value;
                    FixupCampaign(previousValue);
                }
            }
        }
        private Campaign _campaign;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCampaign(Campaign previousValue)
        {
            if (previousValue != null && previousValue.CampaignMailLogs.Contains(this))
            {
                previousValue.CampaignMailLogs.Remove(this);
            }
    
            if (Campaign != null)
            {
                if (!Campaign.CampaignMailLogs.Contains(this))
                {
                    Campaign.CampaignMailLogs.Add(this);
                }
                if (CampaignID != Campaign.CampaignID)
                {
                    CampaignID = Campaign.CampaignID;
                }
            }
            else if (!_settingFK)
            {
                CampaignID = null;
            }
        }

        #endregion

    }
}
