//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class CountryParameter
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual string CountryName
        {
            get { return _countryName; }
            set
            {
                if (_countryName != value)
                {
                    if (Country != null && Country.CountryName != value)
                    {
                        Country = null;
                    }
                    _countryName = value;
                }
            }
        }
        private string _countryName;
    
        public virtual string Parameter
        {
            get;
            set;
        }
    
        public virtual string ParaDesc
        {
            get;
            set;
        }
    
        public virtual string ParaValue
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (CountryName == null) {
						 error_message.Add(new ErrorMessage("CountryName", "CountryName can not be Null "));
				}
		 if (Parameter == null) {
						 error_message.Add(new ErrorMessage("Parameter", "Parameter can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(CountryParameter); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual Country Country
        {
            get { return _country; }
            set
            {
                if (!ReferenceEquals(_country, value))
                {
                    var previousValue = _country;
                    _country = value;
                    FixupCountry(previousValue);
                }
            }
        }
        private Country _country;

        #endregion

        #region Association Fixup
    
        private void FixupCountry(Country previousValue)
        {
            if (previousValue != null && previousValue.CountryParameters.Contains(this))
            {
                previousValue.CountryParameters.Remove(this);
            }
    
            if (Country != null)
            {
                if (!Country.CountryParameters.Contains(this))
                {
                    Country.CountryParameters.Add(this);
                }
                if (CountryName != Country.CountryName)
                {
                    CountryName = Country.CountryName;
                }
            }
        }

        #endregion

    }
}
