//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class CTOSComparision
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string StoreID
        {
            get { return _storeID; }
            set
            {
                if (_storeID != value)
                {
                    if (Product != null && Product.StoreID != value)
                    {
                        Product = null;
                    }
                    _storeID = value;
                }
            }
        }
        private string _storeID;
    
        public virtual string SproductID
        {
            get { return _sproductID; }
            set
            {
                if (_sproductID != value)
                {
                    if (Product != null && Product.SProductID != value)
                    {
                        Product = null;
                    }
                    _sproductID = value;
                }
            }
        }
        private string _sproductID;
    
        public virtual int AttrID
        {
            get;
            set;
        }
    
        public virtual int AttrValueID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Sequence
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (StoreID == null) {
						 error_message.Add(new ErrorMessage("StoreID", "StoreID can not be Null "));
				}
		 if (SproductID == null) {
						 error_message.Add(new ErrorMessage("SproductID", "SproductID can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(CTOSComparision); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual Product Product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    FixupProduct(previousValue);
                }
            }
        }
        private Product _product;

        #endregion

        #region Association Fixup
    
        private void FixupProduct(Product previousValue)
        {
            if (previousValue != null && previousValue.CTOSComparisions.Contains(this))
            {
                previousValue.CTOSComparisions.Remove(this);
            }
    
            if (Product != null)
            {
                if (!Product.CTOSComparisions.Contains(this))
                {
                    Product.CTOSComparisions.Add(this);
                }
                if (StoreID != Product.StoreID)
                {
                    StoreID = Product.StoreID;
                }
                if (SproductID != Product.SProductID)
                {
                    SproductID = Product.SProductID;
                }
            }
        }

        #endregion

    }
}
