//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class KitThemeMappingDetail
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MappingId
        {
            get { return _mappingId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_mappingId != value)
                    {
                        if (KitThemeMapping != null && KitThemeMapping.Id != value)
                        {
                            KitThemeMapping = null;
                        }
                        _mappingId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _mappingId;
    
        public virtual string Doc
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Seq
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(KitThemeMappingDetail); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual KitThemeMapping KitThemeMapping
        {
            get { return _kitThemeMapping; }
            set
            {
                if (!ReferenceEquals(_kitThemeMapping, value))
                {
                    var previousValue = _kitThemeMapping;
                    _kitThemeMapping = value;
                    FixupKitThemeMapping(previousValue);
                }
            }
        }
        private KitThemeMapping _kitThemeMapping;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupKitThemeMapping(KitThemeMapping previousValue)
        {
            if (previousValue != null && previousValue.KitThemeMappingDetails.Contains(this))
            {
                previousValue.KitThemeMappingDetails.Remove(this);
            }
    
            if (KitThemeMapping != null)
            {
                if (!KitThemeMapping.KitThemeMappingDetails.Contains(this))
                {
                    KitThemeMapping.KitThemeMappingDetails.Add(this);
                }
                if (MappingId != KitThemeMapping.Id)
                {
                    MappingId = KitThemeMapping.Id;
                }
            }
            else if (!_settingFK)
            {
                MappingId = null;
            }
        }

        #endregion

    }
}
