//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class Language
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Location
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (Code == null) {
						 error_message.Add(new ErrorMessage("Code", "Code can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(Language); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual ICollection<PStore> Stores
        {
            get
            {
                if (_stores == null)
                {
                    var newCollection = new FixupCollection<PStore>();
                    newCollection.CollectionChanged += FixupStores;
                    _stores = newCollection;
                }
                return _stores;
            }
            set
            {
                if (!ReferenceEquals(_stores, value))
                {
                    var previousValue = _stores as FixupCollection<PStore>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStores;
                    }
                    _stores = value;
                    var newValue = value as FixupCollection<PStore>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStores;
                    }
                }
            }
        }
        private ICollection<PStore> _stores;
    
        public virtual ICollection<PolicyGlobalResource> PolicyGlobalResources
        {
            get
            {
                if (_policyGlobalResources == null)
                {
                    var newCollection = new FixupCollection<PolicyGlobalResource>();
                    newCollection.CollectionChanged += FixupPolicyGlobalResources;
                    _policyGlobalResources = newCollection;
                }
                return _policyGlobalResources;
            }
            set
            {
                if (!ReferenceEquals(_policyGlobalResources, value))
                {
                    var previousValue = _policyGlobalResources as FixupCollection<PolicyGlobalResource>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPolicyGlobalResources;
                    }
                    _policyGlobalResources = value;
                    var newValue = value as FixupCollection<PolicyGlobalResource>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPolicyGlobalResources;
                    }
                }
            }
        }
        private ICollection<PolicyGlobalResource> _policyGlobalResources;
    
        public virtual ICollection<SolutionGlobalResource> SolutionGlobalResources
        {
            get
            {
                if (_solutionGlobalResources == null)
                {
                    var newCollection = new FixupCollection<SolutionGlobalResource>();
                    newCollection.CollectionChanged += FixupSolutionGlobalResources;
                    _solutionGlobalResources = newCollection;
                }
                return _solutionGlobalResources;
            }
            set
            {
                if (!ReferenceEquals(_solutionGlobalResources, value))
                {
                    var previousValue = _solutionGlobalResources as FixupCollection<SolutionGlobalResource>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSolutionGlobalResources;
                    }
                    _solutionGlobalResources = value;
                    var newValue = value as FixupCollection<SolutionGlobalResource>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSolutionGlobalResources;
                    }
                }
            }
        }
        private ICollection<SolutionGlobalResource> _solutionGlobalResources;

        #endregion

        #region Association Fixup
    
        private void FixupStores(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PStore item in e.NewItems)
                {
                    item.Language = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PStore item in e.OldItems)
                {
                    if (ReferenceEquals(item.Language, this))
                    {
                        item.Language = null;
                    }
                }
            }
        }
    
        private void FixupPolicyGlobalResources(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PolicyGlobalResource item in e.NewItems)
                {
                    item.Language = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PolicyGlobalResource item in e.OldItems)
                {
                    if (ReferenceEquals(item.Language, this))
                    {
                        item.Language = null;
                    }
                }
            }
        }
    
        private void FixupSolutionGlobalResources(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SolutionGlobalResource item in e.NewItems)
                {
                    item.Language = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SolutionGlobalResource item in e.OldItems)
                {
                    if (ReferenceEquals(item.Language, this))
                    {
                        item.Language = null;
                    }
                }
            }
        }

        #endregion

    }
}
