//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class Member
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int USER_ID
        {
            get;
            set;
        }
    
        public virtual string COMPANY_ID
        {
            get;
            set;
        }
    
        public virtual string COMPANY_NAME
        {
            get;
            set;
        }
    
        public virtual string LOGIN_PASSWORD
        {
            get;
            set;
        }
    
        public virtual string FIRST_NAME
        {
            get;
            set;
        }
    
        public virtual string LAST_NAME
        {
            get;
            set;
        }
    
        public virtual string EMAIL_ADDR
        {
            get;
            set;
        }
    
        public virtual string EMAIL_ADDR2
        {
            get;
            set;
        }
    
        public virtual string MOBILE
        {
            get;
            set;
        }
    
        public virtual string TEL_AREACODE
        {
            get;
            set;
        }
    
        public virtual string TEL_NO
        {
            get;
            set;
        }
    
        public virtual string TEL_EXT
        {
            get;
            set;
        }
    
        public virtual string FAX_NO
        {
            get;
            set;
        }
    
        public virtual System.DateTime DATE_LAST_CHANGED
        {
            get;
            set;
        }
    
        public virtual System.DateTime DATE_REGISTERED
        {
            get;
            set;
        }
    
        public virtual string JOB_TITLE
        {
            get;
            set;
        }
    
        public virtual string JOB_FUNCTION
        {
            get;
            set;
        }
    
        public virtual string DEPARTMENT
        {
            get;
            set;
        }
    
        public virtual string URL
        {
            get;
            set;
        }
    
        public virtual string PRIMARY_ORG_ID
        {
            get;
            set;
        }
    
        public virtual string CREATED_BY
        {
            get;
            set;
        }
    
        public virtual string Business_Application_Area
        {
            get;
            set;
        }
    
        public virtual string Business_Type
        {
            get;
            set;
        }
    
        public virtual string COUNTRY
        {
            get;
            set;
        }
    
        public virtual Nullable<int> I_COOKIE
        {
            get;
            set;
        }
    
        public virtual string ADDRESS
        {
            get;
            set;
        }
    
        public virtual string ADDRESS2
        {
            get;
            set;
        }
    
        public virtual string CITY
        {
            get;
            set;
        }
    
        public virtual string ZIP
        {
            get;
            set;
        }
    
        public virtual string STATE
        {
            get;
            set;
        }
    
        public virtual string IN_PRODUCT
        {
            get;
            set;
        }
    
        public virtual string SOURCE
        {
            get;
            set;
        }
    
        public virtual string Create_byuser
        {
            get;
            set;
        }
    
        public virtual string ERPID
        {
            get;
            set;
        }
    
        public virtual string SIEBEL_RAW_ID
        {
            get;
            set;
        }
    
        public virtual string SIEBEL_STATUS
        {
            get;
            set;
        }
    
        public virtual string User_Status
        {
            get;
            set;
        }
    
        public virtual string Contact_approach
        {
            get;
            set;
        }
    
        public virtual string Learn_from
        {
            get;
            set;
        }
    
        public virtual string HowBuy
        {
            get;
            set;
        }
    
        public virtual string notify
        {
            get;
            set;
        }
    
        public virtual string ShipTo_Address
        {
            get;
            set;
        }
    
        public virtual string BillTo_Address
        {
            get;
            set;
        }
    
        public virtual string AxSC_Location
        {
            get;
            set;
        }
    
        public virtual string VAT_Number
        {
            get;
            set;
        }
    
        public virtual string activateID
        {
            get;
            set;
        }
    
        public virtual string canseeorder
        {
            get;
            set;
        }
    
        public virtual string lang_prefer
        {
            get;
            set;
        }
    
        public virtual string Reseller_ID
        {
            get;
            set;
        }
    
        public virtual string CNPJ
        {
            get;
            set;
        }
    
        public virtual string INSC
        {
            get;
            set;
        }
    
        public virtual string Promotion_Code
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Channelid
        {
            get;
            set;
        }
    
        public virtual string Channelname
        {
            get;
            set;
        }
    
        public virtual string Channelweb
        {
            get;
            set;
        }
    
        public virtual string Channelcontact
        {
            get;
            set;
        }
    
        public virtual string CPTYPE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Insert_date
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Birthday
        {
            get;
            set;
        }
    
        public virtual string LegalForm
        {
            get;
            set;
        }
    
        public virtual string IN_PRODUCT_VALUES
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> SimpleFormID
        {
            get;
            set;
        }
    
        public virtual string RegPurpose
        {
            get;
            set;
        }
    
        public virtual string SiebelContactRowID
        {
            get;
            set;
        }
    
        public virtual string utm_source
        {
            get;
            set;
        }
    
        public virtual string utm_medium
        {
            get;
            set;
        }
    
        public virtual string utm_campaign
        {
            get;
            set;
        }
    
        public virtual string referrer
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (LOGIN_PASSWORD == null) {
						 error_message.Add(new ErrorMessage("LOGIN_PASSWORD", "LOGIN_PASSWORD can not be Null "));
				}
		 if (EMAIL_ADDR == null) {
						 error_message.Add(new ErrorMessage("EMAIL_ADDR", "EMAIL_ADDR can not be Null "));
				}
		 if (User_Status == null) {
						 error_message.Add(new ErrorMessage("User_Status", "User_Status can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(Member); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

    }
}
