//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class PeripheralsubCatagory
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int subCatagoryID
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual int catagoryID
        {
            get { return _catagoryID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_catagoryID != value)
                    {
                        if (PeripheralCatagory != null && PeripheralCatagory.catagoryID != value)
                        {
                            PeripheralCatagory = null;
                        }
                        _catagoryID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _catagoryID;
    
        public virtual string StoreID
        {
            get { return _storeID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_storeID != value)
                    {
                        if (Store != null && Store.StoreID != value)
                        {
                            Store = null;
                        }
                        _storeID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _storeID;

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(PeripheralsubCatagory); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual PeripheralCatagory PeripheralCatagory
        {
            get { return _peripheralCatagory; }
            set
            {
                if (!ReferenceEquals(_peripheralCatagory, value))
                {
                    var previousValue = _peripheralCatagory;
                    _peripheralCatagory = value;
                    FixupPeripheralCatagory(previousValue);
                }
            }
        }
        private PeripheralCatagory _peripheralCatagory;
    
        public virtual Store Store
        {
            get { return _store; }
            set
            {
                if (!ReferenceEquals(_store, value))
                {
                    var previousValue = _store;
                    _store = value;
                    FixupStore(previousValue);
                }
            }
        }
        private Store _store;
    
        public virtual ICollection<PeripheralProduct> PeripheralProducts
        {
            get
            {
                if (_peripheralProducts == null)
                {
                    var newCollection = new FixupCollection<PeripheralProduct>();
                    newCollection.CollectionChanged += FixupPeripheralProducts;
                    _peripheralProducts = newCollection;
                }
                return _peripheralProducts;
            }
            set
            {
                if (!ReferenceEquals(_peripheralProducts, value))
                {
                    var previousValue = _peripheralProducts as FixupCollection<PeripheralProduct>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPeripheralProducts;
                    }
                    _peripheralProducts = value;
                    var newValue = value as FixupCollection<PeripheralProduct>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPeripheralProducts;
                    }
                }
            }
        }
        private ICollection<PeripheralProduct> _peripheralProducts;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupPeripheralCatagory(PeripheralCatagory previousValue)
        {
            if (previousValue != null && previousValue.PeripheralsubCatagories.Contains(this))
            {
                previousValue.PeripheralsubCatagories.Remove(this);
            }
    
            if (PeripheralCatagory != null)
            {
                if (!PeripheralCatagory.PeripheralsubCatagories.Contains(this))
                {
                    PeripheralCatagory.PeripheralsubCatagories.Add(this);
                }
                if (catagoryID != PeripheralCatagory.catagoryID)
                {
                    catagoryID = PeripheralCatagory.catagoryID;
                }
            }
        }
    
        private void FixupStore(Store previousValue)
        {
            if (Store != null)
            {
                if (StoreID != Store.StoreID)
                {
                    StoreID = Store.StoreID;
                }
            }
            else if (!_settingFK)
            {
                StoreID = null;
            }
        }
    
        private void FixupPeripheralProducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PeripheralProduct item in e.NewItems)
                {
                    item.PeripheralsubCatagory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PeripheralProduct item in e.OldItems)
                {
                    if (ReferenceEquals(item.PeripheralsubCatagory, this))
                    {
                        item.PeripheralsubCatagory = null;
                    }
                }
            }
        }

        #endregion

    }
}
