//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class PolicyCategory
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string StoreID
        {
            get { return _storeID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_storeID != value)
                    {
                        if (Store != null && Store.StoreID != value)
                        {
                            Store = null;
                        }
                        _storeID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _storeID;
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual string LastUpdateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastUpdateDate
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ParentId
        {
            get { return _parentId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_parentId != value)
                    {
                        if (ParentCategory != null && ParentCategory.Id != value)
                        {
                            ParentCategory = null;
                        }
                        _parentId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _parentId;
    
        public virtual string CustomerURL
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PolicyId
        {
            get { return _policyId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_policyId != value)
                    {
                        if (Policy != null && Policy.Id != value)
                        {
                            Policy = null;
                        }
                        _policyId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _policyId;
    
        public virtual bool PublishStatus
        {
            get;
            set;
        }
    
        public virtual string StoreUrl
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (StoreID == null) {
						 error_message.Add(new ErrorMessage("StoreID", "StoreID can not be Null "));
				}
		 if (CreatedBy == null) {
						 error_message.Add(new ErrorMessage("CreatedBy", "CreatedBy can not be Null "));
				}
		 if (Name == null) {
						 error_message.Add(new ErrorMessage("Name", "Name can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(PolicyCategory); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual Policy Policy
        {
            get { return _policy; }
            set
            {
                if (!ReferenceEquals(_policy, value))
                {
                    var previousValue = _policy;
                    _policy = value;
                    FixupPolicy(previousValue);
                }
            }
        }
        private Policy _policy;
    
        public virtual ICollection<PolicyCategory> SubCategories
        {
            get
            {
                if (_subCategories == null)
                {
                    var newCollection = new FixupCollection<PolicyCategory>();
                    newCollection.CollectionChanged += FixupSubCategories;
                    _subCategories = newCollection;
                }
                return _subCategories;
            }
            set
            {
                if (!ReferenceEquals(_subCategories, value))
                {
                    var previousValue = _subCategories as FixupCollection<PolicyCategory>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSubCategories;
                    }
                    _subCategories = value;
                    var newValue = value as FixupCollection<PolicyCategory>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSubCategories;
                    }
                }
            }
        }
        private ICollection<PolicyCategory> _subCategories;
    
        public virtual PolicyCategory ParentCategory
        {
            get { return _parentCategory; }
            set
            {
                if (!ReferenceEquals(_parentCategory, value))
                {
                    var previousValue = _parentCategory;
                    _parentCategory = value;
                    FixupParentCategory(previousValue);
                }
            }
        }
        private PolicyCategory _parentCategory;
    
        public virtual Store Store
        {
            get { return _store; }
            set
            {
                if (!ReferenceEquals(_store, value))
                {
                    var previousValue = _store;
                    _store = value;
                    FixupStore(previousValue);
                }
            }
        }
        private Store _store;
    
        public virtual ICollection<PolicyCategoryGlobalResource> PolicyCategoryGlobalResources
        {
            get
            {
                if (_policyCategoryGlobalResources == null)
                {
                    var newCollection = new FixupCollection<PolicyCategoryGlobalResource>();
                    newCollection.CollectionChanged += FixupPolicyCategoryGlobalResources;
                    _policyCategoryGlobalResources = newCollection;
                }
                return _policyCategoryGlobalResources;
            }
            set
            {
                if (!ReferenceEquals(_policyCategoryGlobalResources, value))
                {
                    var previousValue = _policyCategoryGlobalResources as FixupCollection<PolicyCategoryGlobalResource>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPolicyCategoryGlobalResources;
                    }
                    _policyCategoryGlobalResources = value;
                    var newValue = value as FixupCollection<PolicyCategoryGlobalResource>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPolicyCategoryGlobalResources;
                    }
                }
            }
        }
        private ICollection<PolicyCategoryGlobalResource> _policyCategoryGlobalResources;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupPolicy(Policy previousValue)
        {
            if (previousValue != null && previousValue.PolicyCategories.Contains(this))
            {
                previousValue.PolicyCategories.Remove(this);
            }
    
            if (Policy != null)
            {
                if (!Policy.PolicyCategories.Contains(this))
                {
                    Policy.PolicyCategories.Add(this);
                }
                if (PolicyId != Policy.Id)
                {
                    PolicyId = Policy.Id;
                }
            }
            else if (!_settingFK)
            {
                PolicyId = null;
            }
        }
    
        private void FixupParentCategory(PolicyCategory previousValue)
        {
            if (previousValue != null && previousValue.SubCategories.Contains(this))
            {
                previousValue.SubCategories.Remove(this);
            }
    
            if (ParentCategory != null)
            {
                if (!ParentCategory.SubCategories.Contains(this))
                {
                    ParentCategory.SubCategories.Add(this);
                }
                if (ParentId != ParentCategory.Id)
                {
                    ParentId = ParentCategory.Id;
                }
            }
            else if (!_settingFK)
            {
                ParentId = null;
            }
        }
    
        private void FixupStore(Store previousValue)
        {
            if (previousValue != null && previousValue.PolicyCategories.Contains(this))
            {
                previousValue.PolicyCategories.Remove(this);
            }
    
            if (Store != null)
            {
                if (!Store.PolicyCategories.Contains(this))
                {
                    Store.PolicyCategories.Add(this);
                }
                if (StoreID != Store.StoreID)
                {
                    StoreID = Store.StoreID;
                }
            }
        }
    
        private void FixupSubCategories(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PolicyCategory item in e.NewItems)
                {
                    item.ParentCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PolicyCategory item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParentCategory, this))
                    {
                        item.ParentCategory = null;
                    }
                }
            }
        }
    
        private void FixupPolicyCategoryGlobalResources(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PolicyCategoryGlobalResource item in e.NewItems)
                {
                    item.PolicyCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PolicyCategoryGlobalResource item in e.OldItems)
                {
                    if (ReferenceEquals(item.PolicyCategory, this))
                    {
                        item.PolicyCategory = null;
                    }
                }
            }
        }

        #endregion

    }
}
