//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class ProductSearchOptimizedResult
    {
        #region Primitive Properties
    
        public string SProductID
        {
            get;
            set;
        }
    
        public Nullable<int> CategoryID
        {
            get;
            set;
        }
    
        public string DisplayPartno
        {
            get;
            set;
        }
    
        public string ProductDesc
        {
            get;
            set;
        }
    
        public Nullable<decimal> ListingPrice
        {
            get;
            set;
        }
    
        public string ImageID
        {
            get;
            set;
        }
    
        public string StoreUrl
        {
            get;
            set;
        }
    
        public Nullable<int> RANK
        {
            get;
            set;
        }
    
        public string Group
        {
            get;
            set;
        }
    
        public Nullable<int> Priority
        {
            get;
            set;
        }
    
        public Nullable<int> MarketingStatus
        {
            get;
            set;
        }
    
        public Nullable<int> ProCount
        {
            get;
            set;
        }

        #endregion

    }
}
