//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class ProductCategoryMetadata
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string FieldName
        {
            get;
            set;
        }
    
        public virtual short OrdinalNo
        {
            get;
            set;
        }
    
        public virtual bool Status
        {
            get;
            set;
        }
    
        public virtual bool PublishStatus
        {
            get;
            set;
        }
    
        public virtual int ProductCategoryId
        {
            get { return _productCategoryId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_productCategoryId != value)
                    {
                        if (ProductCategory != null && ProductCategory.Id != value)
                        {
                            ProductCategory = null;
                        }
                        _productCategoryId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _productCategoryId;
    
        public virtual string FieldCaption
        {
            get;
            set;
        }
    
        public virtual string FieldConstraint
        {
            get;
            set;
        }
    
        public virtual string FieldDescription
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ProductCategoryMetadataGroupId
        {
            get { return _productCategoryMetadataGroupId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_productCategoryMetadataGroupId != value)
                    {
                        if (ProductCategoryMetadataGroup != null && ProductCategoryMetadataGroup.Id != value)
                        {
                            ProductCategoryMetadataGroup = null;
                        }
                        _productCategoryMetadataGroupId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _productCategoryMetadataGroupId;
    
        public virtual Nullable<bool> ShowOnStore
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (FieldName == null) {
						 error_message.Add(new ErrorMessage("FieldName", "FieldName can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(ProductCategoryMetadata); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual PStoreProductCategory ProductCategory
        {
            get { return _productCategory; }
            set
            {
                if (!ReferenceEquals(_productCategory, value))
                {
                    var previousValue = _productCategory;
                    _productCategory = value;
                    FixupProductCategory(previousValue);
                }
            }
        }
        private PStoreProductCategory _productCategory;
    
        public virtual ProductCategoryMetadataGroup ProductCategoryMetadataGroup
        {
            get { return _productCategoryMetadataGroup; }
            set
            {
                if (!ReferenceEquals(_productCategoryMetadataGroup, value))
                {
                    var previousValue = _productCategoryMetadataGroup;
                    _productCategoryMetadataGroup = value;
                    FixupProductCategoryMetadataGroup(previousValue);
                }
            }
        }
        private ProductCategoryMetadataGroup _productCategoryMetadataGroup;
    
        public virtual ICollection<ProductCategoryMetadataValue> ProductCategoryMetadataValues
        {
            get
            {
                if (_productCategoryMetadataValues == null)
                {
                    var newCollection = new FixupCollection<ProductCategoryMetadataValue>();
                    newCollection.CollectionChanged += FixupProductCategoryMetadataValues;
                    _productCategoryMetadataValues = newCollection;
                }
                return _productCategoryMetadataValues;
            }
            set
            {
                if (!ReferenceEquals(_productCategoryMetadataValues, value))
                {
                    var previousValue = _productCategoryMetadataValues as FixupCollection<ProductCategoryMetadataValue>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductCategoryMetadataValues;
                    }
                    _productCategoryMetadataValues = value;
                    var newValue = value as FixupCollection<ProductCategoryMetadataValue>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductCategoryMetadataValues;
                    }
                }
            }
        }
        private ICollection<ProductCategoryMetadataValue> _productCategoryMetadataValues;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupProductCategory(PStoreProductCategory previousValue)
        {
            if (previousValue != null && previousValue.ProductCategoryMetadatas.Contains(this))
            {
                previousValue.ProductCategoryMetadatas.Remove(this);
            }
    
            if (ProductCategory != null)
            {
                if (!ProductCategory.ProductCategoryMetadatas.Contains(this))
                {
                    ProductCategory.ProductCategoryMetadatas.Add(this);
                }
                if (ProductCategoryId != ProductCategory.Id)
                {
                    ProductCategoryId = ProductCategory.Id;
                }
            }
        }
    
        private void FixupProductCategoryMetadataGroup(ProductCategoryMetadataGroup previousValue)
        {
            if (previousValue != null && previousValue.ProductCategoryMetadatas.Contains(this))
            {
                previousValue.ProductCategoryMetadatas.Remove(this);
            }
    
            if (ProductCategoryMetadataGroup != null)
            {
                if (!ProductCategoryMetadataGroup.ProductCategoryMetadatas.Contains(this))
                {
                    ProductCategoryMetadataGroup.ProductCategoryMetadatas.Add(this);
                }
                if (ProductCategoryMetadataGroupId != ProductCategoryMetadataGroup.Id)
                {
                    ProductCategoryMetadataGroupId = ProductCategoryMetadataGroup.Id;
                }
            }
            else if (!_settingFK)
            {
                ProductCategoryMetadataGroupId = null;
            }
        }
    
        private void FixupProductCategoryMetadataValues(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductCategoryMetadataValue item in e.NewItems)
                {
                    item.ProductCategoryMetadata = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductCategoryMetadataValue item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductCategoryMetadata, this))
                    {
                        item.ProductCategoryMetadata = null;
                    }
                }
            }
        }

        #endregion

    }
}
