//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class PStoreProduct : Part
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PStoreId
        {
            get { return _pStoreId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_pStoreId != value)
                    {
                        if (Store != null && Store.Id != value)
                        {
                            Store = null;
                        }
                        _pStoreId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _pStoreId;
    
        public virtual Nullable<int> PSProductId
        {
            get { return _pSProductId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_pSProductId != value)
                    {
                        if (StoreProduct != null && StoreProduct.Id != value)
                        {
                            StoreProduct = null;
                        }
                        _pSProductId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _pSProductId;
    
        public virtual Nullable<int> PProductId
        {
            get;
            set;
        }
    
        public virtual string Manufacturer
        {
            get;
            set;
        }
    
        public virtual int OrdinalNo
        {
            get;
            set;
        }
    
        public virtual bool IsSoldInBundleOnly
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartFrom
        {
            get;
            set;
        }
    
        public virtual System.DateTime ExpireDate
        {
            get;
            set;
        }
    
        public virtual string Note
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ReplacementStoreProductId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PhaseInDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PhaseOutDate
        {
            get;
            set;
        }
    
        public virtual string LargeSizeImageUrl
        {
            get;
            set;
        }
    
        public virtual string MediumSizeImageUrl
        {
            get;
            set;
        }
    
        public virtual string SmallSizeImageUrl
        {
            get;
            set;
        }
    
        public virtual string IconImageUrl
        {
            get;
            set;
        }
    
        public virtual int ProductCategoryId
        {
            get;
            set;
        }
    
        public virtual int LeadTime
        {
            get;
            set;
        }
    
        public virtual decimal Markup
        {
            get;
            set;
        }
    
        public virtual decimal Price
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> FreeShipping
        {
            get;
            set;
        }
    
        public virtual string ShipFrom
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> CallForPrice
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LimitQty
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> PTDCost
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SpecialShipment
        {
            get;
            set;
        }
    
        public virtual string MetaKeyword
        {
            get;
            set;
        }
    
        public virtual string MetaTitle
        {
            get;
            set;
        }
    
        public virtual string MetaDescription
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SpecialOrder
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(PStoreProduct); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual PStore Store
        {
            get { return _store; }
            set
            {
                if (!ReferenceEquals(_store, value))
                {
                    var previousValue = _store;
                    _store = value;
                    FixupStore(previousValue);
                }
            }
        }
        private PStore _store;
    
        public virtual StoreProduct StoreProduct
        {
            get { return _storeProduct; }
            set
            {
                if (!ReferenceEquals(_storeProduct, value))
                {
                    var previousValue = _storeProduct;
                    _storeProduct = value;
                    FixupStoreProduct(previousValue);
                }
            }
        }
        private StoreProduct _storeProduct;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupStore(PStore previousValue)
        {
            if (previousValue != null && previousValue.PStoreProducts.Contains(this))
            {
                previousValue.PStoreProducts.Remove(this);
            }
    
            if (Store != null)
            {
                if (!Store.PStoreProducts.Contains(this))
                {
                    Store.PStoreProducts.Add(this);
                }
                if (PStoreId != Store.Id)
                {
                    PStoreId = Store.Id;
                }
            }
            else if (!_settingFK)
            {
                PStoreId = null;
            }
        }
    
        private void FixupStoreProduct(StoreProduct previousValue)
        {
            if (previousValue != null && previousValue.PStoreProducts.Contains(this))
            {
                previousValue.PStoreProducts.Remove(this);
            }
    
            if (StoreProduct != null)
            {
                if (!StoreProduct.PStoreProducts.Contains(this))
                {
                    StoreProduct.PStoreProducts.Add(this);
                }
                if (PSProductId != StoreProduct.Id)
                {
                    PSProductId = StoreProduct.Id;
                }
            }
            else if (!_settingFK)
            {
                PSProductId = null;
            }
        }

        #endregion

    }
}
