//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class RateServiceName
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual string CarierName
        {
            get { return _carierName; }
            set
            {
                if (_carierName != value)
                {
                    if (ShippingCarier != null && ShippingCarier.CarierName != value)
                    {
                        ShippingCarier = null;
                    }
                    _carierName = value;
                }
            }
        }
        private string _carierName;
    
        public virtual string MessageCode
        {
            get;
            set;
        }
    
        public virtual string DefaultServiceName
        {
            get;
            set;
        }
    
        public virtual string AdvantechCode
        {
            get;
            set;
        }
    
        public virtual string SupportedRegion
        {
            get;
            set;
        }
    
        public virtual string FreigthExType
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (CarierName == null) {
						 error_message.Add(new ErrorMessage("CarierName", "CarierName can not be Null "));
				}
		 if (MessageCode == null) {
						 error_message.Add(new ErrorMessage("MessageCode", "MessageCode can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(RateServiceName); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual ICollection<RateServiceMessageLang> RateServiceMessageLangs
        {
            get
            {
                if (_rateServiceMessageLangs == null)
                {
                    var newCollection = new FixupCollection<RateServiceMessageLang>();
                    newCollection.CollectionChanged += FixupRateServiceMessageLangs;
                    _rateServiceMessageLangs = newCollection;
                }
                return _rateServiceMessageLangs;
            }
            set
            {
                if (!ReferenceEquals(_rateServiceMessageLangs, value))
                {
                    var previousValue = _rateServiceMessageLangs as FixupCollection<RateServiceMessageLang>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRateServiceMessageLangs;
                    }
                    _rateServiceMessageLangs = value;
                    var newValue = value as FixupCollection<RateServiceMessageLang>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRateServiceMessageLangs;
                    }
                }
            }
        }
        private ICollection<RateServiceMessageLang> _rateServiceMessageLangs;
    
        public virtual ShippingCarier ShippingCarier
        {
            get { return _shippingCarier; }
            set
            {
                if (!ReferenceEquals(_shippingCarier, value))
                {
                    var previousValue = _shippingCarier;
                    _shippingCarier = value;
                    FixupShippingCarier(previousValue);
                }
            }
        }
        private ShippingCarier _shippingCarier;

        #endregion

        #region Association Fixup
    
        private void FixupShippingCarier(ShippingCarier previousValue)
        {
            if (previousValue != null && previousValue.RateServiceNames.Contains(this))
            {
                previousValue.RateServiceNames.Remove(this);
            }
    
            if (ShippingCarier != null)
            {
                if (!ShippingCarier.RateServiceNames.Contains(this))
                {
                    ShippingCarier.RateServiceNames.Add(this);
                }
                if (CarierName != ShippingCarier.CarierName)
                {
                    CarierName = ShippingCarier.CarierName;
                }
            }
        }
    
        private void FixupRateServiceMessageLangs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RateServiceMessageLang item in e.NewItems)
                {
                    item.RateServiceName = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RateServiceMessageLang item in e.OldItems)
                {
                    if (ReferenceEquals(item.RateServiceName, this))
                    {
                        item.RateServiceName = null;
                    }
                }
            }
        }

        #endregion

    }
}
