//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class RuleSetDetail
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int RuleSetId
        {
            get { return _ruleSetId; }
            set
            {
                if (_ruleSetId != value)
                {
                    if (RuleSet != null && RuleSet.RuleSetID != value)
                    {
                        RuleSet = null;
                    }
                    _ruleSetId = value;
                }
            }
        }
        private int _ruleSetId;
    
        public virtual int RuleID
        {
            get;
            set;
        }
    
        public virtual int AttributeCatId
        {
            get;
            set;
        }
    
        public virtual int AttributeId
        {
            get;
            set;
        }
    
        public virtual int AttributeValueId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AttributeStartRange
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AttributeEndRage
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(RuleSetDetail); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual RuleSet RuleSet
        {
            get { return _ruleSet; }
            set
            {
                if (!ReferenceEquals(_ruleSet, value))
                {
                    var previousValue = _ruleSet;
                    _ruleSet = value;
                    FixupRuleSet(previousValue);
                }
            }
        }
        private RuleSet _ruleSet;

        #endregion

        #region Association Fixup
    
        private void FixupRuleSet(RuleSet previousValue)
        {
            if (previousValue != null && previousValue.RuleSetDetails.Contains(this))
            {
                previousValue.RuleSetDetails.Remove(this);
            }
    
            if (RuleSet != null)
            {
                if (!RuleSet.RuleSetDetails.Contains(this))
                {
                    RuleSet.RuleSetDetails.Add(this);
                }
                if (RuleSetId != RuleSet.RuleSetID)
                {
                    RuleSetId = RuleSet.RuleSetID;
                }
            }
        }

        #endregion

    }
}
