//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class Solution
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string StoreID
        {
            get { return _storeID; }
            set
            {
                if (_storeID != value)
                {
                    if (Store != null && Store.StoreID != value)
                    {
                        Store = null;
                    }
                    _storeID = value;
                }
            }
        }
        private string _storeID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Link
        {
            get;
            set;
        }
    
        public virtual string Image
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual string LastUpdateBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastUpdateDate
        {
            get;
            set;
        }
    
        public virtual bool PublishStatus
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Seq
        {
            get;
            set;
        }
    
        public virtual string BannerFile
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (StoreID == null) {
						 error_message.Add(new ErrorMessage("StoreID", "StoreID can not be Null "));
				}
		 if (Name == null) {
						 error_message.Add(new ErrorMessage("Name", "Name can not be Null "));
				}
		 if (Link == null) {
						 error_message.Add(new ErrorMessage("Link", "Link can not be Null "));
				}
		 if (Image == null) {
						 error_message.Add(new ErrorMessage("Image", "Image can not be Null "));
				}
		 if (CreatedBy == null) {
						 error_message.Add(new ErrorMessage("CreatedBy", "CreatedBy can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(Solution); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual Store Store
        {
            get { return _store; }
            set
            {
                if (!ReferenceEquals(_store, value))
                {
                    var previousValue = _store;
                    _store = value;
                    FixupStore(previousValue);
                }
            }
        }
        private Store _store;
    
        public virtual ICollection<SolutionsAssosociateItem> SolutionsAssosociateItems
        {
            get
            {
                if (_solutionsAssosociateItems == null)
                {
                    var newCollection = new FixupCollection<SolutionsAssosociateItem>();
                    newCollection.CollectionChanged += FixupSolutionsAssosociateItems;
                    _solutionsAssosociateItems = newCollection;
                }
                return _solutionsAssosociateItems;
            }
            set
            {
                if (!ReferenceEquals(_solutionsAssosociateItems, value))
                {
                    var previousValue = _solutionsAssosociateItems as FixupCollection<SolutionsAssosociateItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSolutionsAssosociateItems;
                    }
                    _solutionsAssosociateItems = value;
                    var newValue = value as FixupCollection<SolutionsAssosociateItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSolutionsAssosociateItems;
                    }
                }
            }
        }
        private ICollection<SolutionsAssosociateItem> _solutionsAssosociateItems;
    
        public virtual ICollection<SolutionGlobalResource> SolutionGlobalResources
        {
            get
            {
                if (_solutionGlobalResources == null)
                {
                    var newCollection = new FixupCollection<SolutionGlobalResource>();
                    newCollection.CollectionChanged += FixupSolutionGlobalResources;
                    _solutionGlobalResources = newCollection;
                }
                return _solutionGlobalResources;
            }
            set
            {
                if (!ReferenceEquals(_solutionGlobalResources, value))
                {
                    var previousValue = _solutionGlobalResources as FixupCollection<SolutionGlobalResource>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSolutionGlobalResources;
                    }
                    _solutionGlobalResources = value;
                    var newValue = value as FixupCollection<SolutionGlobalResource>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSolutionGlobalResources;
                    }
                }
            }
        }
        private ICollection<SolutionGlobalResource> _solutionGlobalResources;

        #endregion

        #region Association Fixup
    
        private void FixupStore(Store previousValue)
        {
            if (previousValue != null && previousValue.Solutions.Contains(this))
            {
                previousValue.Solutions.Remove(this);
            }
    
            if (Store != null)
            {
                if (!Store.Solutions.Contains(this))
                {
                    Store.Solutions.Add(this);
                }
                if (StoreID != Store.StoreID)
                {
                    StoreID = Store.StoreID;
                }
            }
        }
    
        private void FixupSolutionsAssosociateItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SolutionsAssosociateItem item in e.NewItems)
                {
                    item.Solution = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SolutionsAssosociateItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.Solution, this))
                    {
                        item.Solution = null;
                    }
                }
            }
        }
    
        private void FixupSolutionGlobalResources(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SolutionGlobalResource item in e.NewItems)
                {
                    item.Solution = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SolutionGlobalResource item in e.OldItems)
                {
                    if (ReferenceEquals(item.Solution, this))
                    {
                        item.Solution = null;
                    }
                }
            }
        }

        #endregion

    }
}
