//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class SpecAttribute
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int AttrID
        {
            get;
            set;
        }
    
        public virtual int AttrCatID
        {
            get { return _attrCatID; }
            set
            {
                if (_attrCatID != value)
                {
                    if (SpecAttributeCat != null && SpecAttributeCat.AttrCatID != value)
                    {
                        SpecAttributeCat = null;
                    }
                    _attrCatID = value;
                }
            }
        }
        private int _attrCatID;
    
        public virtual string AttrName
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(SpecAttribute); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual SpecAttributeCat SpecAttributeCat
        {
            get { return _specAttributeCat; }
            set
            {
                if (!ReferenceEquals(_specAttributeCat, value))
                {
                    var previousValue = _specAttributeCat;
                    _specAttributeCat = value;
                    FixupSpecAttributeCat(previousValue);
                }
            }
        }
        private SpecAttributeCat _specAttributeCat;
    
        public virtual ICollection<SpecAttributelang> SpecAttributelangs
        {
            get
            {
                if (_specAttributelangs == null)
                {
                    var newCollection = new FixupCollection<SpecAttributelang>();
                    newCollection.CollectionChanged += FixupSpecAttributelangs;
                    _specAttributelangs = newCollection;
                }
                return _specAttributelangs;
            }
            set
            {
                if (!ReferenceEquals(_specAttributelangs, value))
                {
                    var previousValue = _specAttributelangs as FixupCollection<SpecAttributelang>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSpecAttributelangs;
                    }
                    _specAttributelangs = value;
                    var newValue = value as FixupCollection<SpecAttributelang>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSpecAttributelangs;
                    }
                }
            }
        }
        private ICollection<SpecAttributelang> _specAttributelangs;
    
        public virtual ICollection<SpecAttributeValue> SpecAttributeValues
        {
            get
            {
                if (_specAttributeValues == null)
                {
                    var newCollection = new FixupCollection<SpecAttributeValue>();
                    newCollection.CollectionChanged += FixupSpecAttributeValues;
                    _specAttributeValues = newCollection;
                }
                return _specAttributeValues;
            }
            set
            {
                if (!ReferenceEquals(_specAttributeValues, value))
                {
                    var previousValue = _specAttributeValues as FixupCollection<SpecAttributeValue>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSpecAttributeValues;
                    }
                    _specAttributeValues = value;
                    var newValue = value as FixupCollection<SpecAttributeValue>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSpecAttributeValues;
                    }
                }
            }
        }
        private ICollection<SpecAttributeValue> _specAttributeValues;

        #endregion

        #region Association Fixup
    
        private void FixupSpecAttributeCat(SpecAttributeCat previousValue)
        {
            if (previousValue != null && previousValue.SpecAttributes.Contains(this))
            {
                previousValue.SpecAttributes.Remove(this);
            }
    
            if (SpecAttributeCat != null)
            {
                if (!SpecAttributeCat.SpecAttributes.Contains(this))
                {
                    SpecAttributeCat.SpecAttributes.Add(this);
                }
                if (AttrCatID != SpecAttributeCat.AttrCatID)
                {
                    AttrCatID = SpecAttributeCat.AttrCatID;
                }
            }
        }
    
        private void FixupSpecAttributelangs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SpecAttributelang item in e.NewItems)
                {
                    item.SpecAttribute = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SpecAttributelang item in e.OldItems)
                {
                    if (ReferenceEquals(item.SpecAttribute, this))
                    {
                        item.SpecAttribute = null;
                    }
                }
            }
        }
    
        private void FixupSpecAttributeValues(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SpecAttributeValue item in e.NewItems)
                {
                    item.SpecAttribute = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SpecAttributeValue item in e.OldItems)
                {
                    if (ReferenceEquals(item.SpecAttribute, this))
                    {
                        item.SpecAttribute = null;
                    }
                }
            }
        }

        #endregion

    }
}
