//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class StoreConfig
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual string aKey
        {
            get { return _aKey; }
            set
            {
                if (_aKey != value)
                {
                    if (StoreConfigKey != null && StoreConfigKey.aKey != value)
                    {
                        StoreConfigKey = null;
                    }
                    _aKey = value;
                }
            }
        }
        private string _aKey;
    
        public virtual string Value
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (aKey == null) {
						 error_message.Add(new ErrorMessage("aKey", "aKey can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(StoreConfig); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual StoreConfigKey StoreConfigKey
        {
            get { return _storeConfigKey; }
            set
            {
                if (!ReferenceEquals(_storeConfigKey, value))
                {
                    var previousValue = _storeConfigKey;
                    _storeConfigKey = value;
                    FixupStoreConfigKey(previousValue);
                }
            }
        }
        private StoreConfigKey _storeConfigKey;

        #endregion

        #region Association Fixup
    
        private void FixupStoreConfigKey(StoreConfigKey previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.StoreConfig, this))
            {
                previousValue.StoreConfig = null;
            }
    
            if (StoreConfigKey != null)
            {
                StoreConfigKey.StoreConfig = this;
                if (aKey != StoreConfigKey.aKey)
                {
                    aKey = StoreConfigKey.aKey;
                }
            }
        }

        #endregion

    }
}
