//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class VSpecRule
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual string ProductNo
        {
            get;
            set;
        }
    
        public virtual string LocalAttributeName
        {
            get;
            set;
        }
    
        public virtual string LocalValueName
        {
            get;
            set;
        }
    
        public virtual string LocalCatName
        {
            get;
            set;
        }
    
        public virtual int AttrValueID
        {
            get;
            set;
        }
    
        public virtual int AttrID
        {
            get;
            set;
        }
    
        public virtual string Storeid
        {
            get;
            set;
        }
    
        public virtual string AttrName
        {
            get;
            set;
        }
    
        public virtual string AttrValueName
        {
            get;
            set;
        }
    
        public virtual string AttrCatName
        {
            get;
            set;
        }
    
        public virtual int CatID
        {
            get;
            set;
        }
    
        public virtual string CategoryPath
        {
            get;
            set;
        }
    
        public virtual string CategoryName
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   		 if (ProductNo == null) {
						 error_message.Add(new ErrorMessage("ProductNo", "ProductNo can not be Null "));
				}
		 if (LocalAttributeName == null) {
						 error_message.Add(new ErrorMessage("LocalAttributeName", "LocalAttributeName can not be Null "));
				}
		 if (LocalValueName == null) {
						 error_message.Add(new ErrorMessage("LocalValueName", "LocalValueName can not be Null "));
				}
		 if (LocalCatName == null) {
						 error_message.Add(new ErrorMessage("LocalCatName", "LocalCatName can not be Null "));
				}
		 if (Storeid == null) {
						 error_message.Add(new ErrorMessage("Storeid", "Storeid can not be Null "));
				}
		 if (AttrName == null) {
						 error_message.Add(new ErrorMessage("AttrName", "AttrName can not be Null "));
				}
		 if (AttrValueName == null) {
						 error_message.Add(new ErrorMessage("AttrValueName", "AttrValueName can not be Null "));
				}
		 if (AttrCatName == null) {
						 error_message.Add(new ErrorMessage("AttrCatName", "AttrCatName can not be Null "));
				}
		 if (CategoryPath == null) {
						 error_message.Add(new ErrorMessage("CategoryPath", "CategoryPath can not be Null "));
				}
		 if (CategoryName == null) {
						 error_message.Add(new ErrorMessage("CategoryName", "CategoryName can not be Null "));
				}

    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(VSpecRule); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

    }
}
