//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using eStore.POCOS.PocoX;
 

namespace eStore.POCOS
{
    public partial class WidgetRequestDetail
    {
        #region Primitive Properties
     
    	public List<ErrorMessage> error_message{
    		get;
    		set;
    	}
    
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> WidgetRequestId
        {
            get { return _widgetRequestId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_widgetRequestId != value)
                    {
                        if (WidgetRequest != null && WidgetRequest.Id != value)
                        {
                            WidgetRequest = null;
                        }
                        _widgetRequestId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _widgetRequestId;
    
        public virtual string Key
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Value
        {
            get;
            set;
        }

        #endregion

        #region Validation
    	
    	public bool validate() {
    		error_message = new List<ErrorMessage>();
    	   
    	   
    	   if(error_message.Count>0) {
    	   	return false;
    	   }else {
    	    return true;
    	   }
    	
    	}
    	
    	/* public void Write()
        {
            Type type = typeof(WidgetRequestDetail); // Get type pointer
             PropertyInfo[] fields = type.GetProperties(); // Obtain all fields
                foreach (var pinfo in fields) // Loop through fields
                {
                    string name = pinfo.Name; // Get string name
                    object temp = pinfo.GetValue(pinfo.Name,null); // Get value
                if (temp is int) // See if it is an integer.
                {
                    int value = (int)temp;
                    Console.Write(name);
                    Console.Write(" (int) = ");
                    Console.WriteLine(value);
                }
                else if (temp is string) // See if it is a string.
                {
                    string value = temp as string;
                    Console.Write(name);
                    Console.Write(" (string) = ");
                    Console.WriteLine(value);
                }
            }
        }*/
     
    	
    	
        #endregion

        #region Navigation Properties
    
        public virtual WidgetRequest WidgetRequest
        {
            get { return _widgetRequest; }
            set
            {
                if (!ReferenceEquals(_widgetRequest, value))
                {
                    var previousValue = _widgetRequest;
                    _widgetRequest = value;
                    FixupWidgetRequest(previousValue);
                }
            }
        }
        private WidgetRequest _widgetRequest;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupWidgetRequest(WidgetRequest previousValue)
        {
            if (previousValue != null && previousValue.WidgetRequestDetails.Contains(this))
            {
                previousValue.WidgetRequestDetails.Remove(this);
            }
    
            if (WidgetRequest != null)
            {
                if (!WidgetRequest.WidgetRequestDetails.Contains(this))
                {
                    WidgetRequest.WidgetRequestDetails.Add(this);
                }
                if (WidgetRequestId != WidgetRequest.Id)
                {
                    WidgetRequestId = WidgetRequest.Id;
                }
            }
            else if (!_settingFK)
            {
                WidgetRequestId = null;
            }
        }

        #endregion

    }
}
