//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace eStore.POCOS.Sync
{
    public partial class es_Config_Item_new
    {
        #region Primitive Properties
    
        public virtual int Con_Item_AutoID
        {
            get;
            set;
        }
    
        public virtual string Con_Item_Number
        {
            get;
            set;
        }
    
        public virtual string Con_Item_virtual_part
        {
            get;
            set;
        }
    
        public virtual string Con_Item_MBID
        {
            get;
            set;
        }
    
        public virtual string Con_Item_Line
        {
            get;
            set;
        }
    
        public virtual string Con_Item_Desc
        {
            get;
            set;
        }
    
        public virtual string Con_Item_Data_Sheet
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Depth_M
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Width_M
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Height_M
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Depth_I
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Width_I
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Height_I
        {
            get;
            set;
        }
    
        public virtual string Con_item_features
        {
            get;
            set;
        }
    
        public virtual string con_item_id
        {
            get;
            set;
        }
    
        public virtual string short_features
        {
            get;
            set;
        }

        #endregion
    }
}
