//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace eStore.POCOS.Sync
{
    public partial class es_sharebomtree
    {
        #region Primitive Properties
    
        public virtual int nodeid
        {
            get;
            set;
        }
    
        public virtual string node_name
        {
            get;
            set;
        }
    
        public virtual string node_desc
        {
            get;
            set;
        }
    
        public virtual string node_parentid
        {
            get;
            set;
        }
    
        public virtual string node_partno_list
        {
            get;
            set;
        }
    
        public virtual string node_type
        {
            get;
            set;
        }
    
        public virtual string node_replacepartno_list
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> node_discount
        {
            get;
            set;
        }
    
        public virtual Nullable<int> node_seq
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<es_cbomtree> es_cbomtree
        {
            get
            {
                if (_es_cbomtree == null)
                {
                    var newCollection = new FixupCollection<es_cbomtree>();
                    newCollection.CollectionChanged += Fixupes_cbomtree;
                    _es_cbomtree = newCollection;
                }
                return _es_cbomtree;
            }
            set
            {
                if (!ReferenceEquals(_es_cbomtree, value))
                {
                    var previousValue = _es_cbomtree as FixupCollection<es_cbomtree>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupes_cbomtree;
                    }
                    _es_cbomtree = value;
                    var newValue = value as FixupCollection<es_cbomtree>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupes_cbomtree;
                    }
                }
            }
        }
        private ICollection<es_cbomtree> _es_cbomtree;

        #endregion
        #region Association Fixup
    
        private void Fixupes_cbomtree(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (es_cbomtree item in e.NewItems)
                {
                    item.es_sharebomtree = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (es_cbomtree item in e.OldItems)
                {
                    if (ReferenceEquals(item.es_sharebomtree, this))
                    {
                        item.es_sharebomtree = null;
                    }
                }
            }
        }

        #endregion
    }
}
