//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace eStore.POCOS.Sync
{
    public partial class PAP
    {
        #region Primitive Properties
    
        public virtual int SN
        {
            get;
            set;
        }
    
        public virtual string Board_Form_Factor
        {
            get;
            set;
        }
    
        public virtual string Board_CPU
        {
            get;
            set;
        }
    
        public virtual string Board_Model_Name
        {
            get;
            set;
        }
    
        public virtual string Monitor_Part_No
        {
            get;
            set;
        }
    
        public virtual string Cable_Type
        {
            get;
            set;
        }
    
        public virtual string Cable_Part_No
        {
            get;
            set;
        }
    
        public virtual string Cable_Bit
        {
            get;
            set;
        }

        #endregion
    }
}
