//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace eStore.POCOS.Sync
{
    public partial class PRODUCT
    {
        #region Primitive Properties
    
        public virtual string PRODUCT_ID
        {
            get;
            set;
        }
    
        public virtual string PART_NO
        {
            get;
            set;
        }
    
        public virtual string PRODUCT_DESC
        {
            get;
            set;
        }
    
        public virtual string PRODUCT_DESC2
        {
            get;
            set;
        }
    
        public virtual string STATUS
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LAST_UPDATED
        {
            get;
            set;
        }
    
        public virtual string LAST_UPDATED_BY
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CREATED
        {
            get;
            set;
        }
    
        public virtual string CREATED_BY
        {
            get;
            set;
        }
    
        public virtual string TUMBNAIL_IMAGE_ID
        {
            get;
            set;
        }
    
        public virtual string IMAGE_ID
        {
            get;
            set;
        }
    
        public virtual string ONLINE_PUBLISH
        {
            get;
            set;
        }
    
        public virtual string EXTENTED_DESC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> NEW_PRODUCT_DATE
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ship_weight
        {
            get;
            set;
        }
    
        public virtual Nullable<double> net_weight
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DimensionW
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DimensionH
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DimensionL
        {
            get;
            set;
        }

        #endregion
    }
}
