//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace eStore.POCOS.Sync
{
    public partial class SAP_PRODUCT_STATUS
    {
        #region Primitive Properties
    
        public virtual string PART_NO
        {
            get;
            set;
        }
    
        public virtual string DLV_PLANT
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> MIN_ORDER_QTY
        {
            get;
            set;
        }

        #endregion
    }
}
