//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace eStore.POCOS.Sync
{
    public partial class V_Spec_V2
    {
        #region Primitive Properties
    
        public virtual string ItemType
        {
            get;
            set;
        }
    
        public virtual string ProductNo
        {
            get;
            set;
        }
    
        public virtual int AttrCatID
        {
            get;
            set;
        }
    
        public virtual string AttrCatName
        {
            get;
            set;
        }
    
        public virtual int AttrID
        {
            get;
            set;
        }
    
        public virtual string AttrName
        {
            get;
            set;
        }
    
        public virtual int AttrValueID
        {
            get;
            set;
        }
    
        public virtual string AttrValueName
        {
            get;
            set;
        }
    
        public virtual int DataSheet_Sequence
        {
            get;
            set;
        }
    
        public virtual bool Is_Filter
        {
            get;
            set;
        }
    
        public virtual string SpecSetID
        {
            get;
            set;
        }

        #endregion
    }
}
