//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStore.UI.Modules {
    
    
    public partial class AutomationHomeContent {
        
        /// <summary>
        /// eStoreLiquidSlider1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStore.UI.Modules.eStoreLiquidSlider eStoreLiquidSlider1;
        
        /// <summary>
        /// liveperson1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStore.UI.Modules.liveperson liveperson1;
        
        /// <summary>
        /// rptTodaysDeals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStore.Presentation.eStoreControls.Repeater rptTodaysDeals;
        
        /// <summary>
        /// elsRewardsAds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStore.UI.Modules.eStoreLiquidSlider elsRewardsAds;
        
        /// <summary>
        /// rpHotProduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStore.Presentation.eStoreControls.Repeater rpHotProduct;
        
        /// <summary>
        /// rpNewProduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStore.Presentation.eStoreControls.Repeater rpNewProduct;
    }
}
